#!/bin/sh

#コンソール出力
echo "hello echo"
printf "hello world\n"
#上書き書き込み
printf "hello external1\n" > text1.txt
#追加書き込み
printf "hello external\n" >> text2.txt
#ヒアドキュメント
text3.txt <<TXT1
aaa
bbb
ccc
TXT1

#############################
#変数
#############################
#変数の代入
aaa=100
#変数の参照
printf "${aaa} is a\n"


#############################
#関数
#############################
func01(){
  printf "func01\n"
}

func01

func02(){
  printf "arg1 is $1\n"
  printf "arg2 is $2\n"
}

func02 100 200

#############################
#引数
#############################

#############################
#ループ
#############################

